export const M = {
  GO_OTHER_PAGE: 'GO_OTHER_PAGE'
  // CHANGE_SEARCH_RESULTS: 'CHANGE_SEARCH_RESULTS',
  // CHANGE_LOCATION: 'CHANGE_LOCATION',
  // OPEN_PLAYER: 'OPEN_PLAYER',
  // CHANGE_PLAYER_SIZE: 'CHANGE_PLAYER_SIZE'
}
