export const M = {
  GO_OTHER_PAGE: 'GO_OTHER_PAGE',
  CHANGE_CHAT_ID: 'CHANGE_CHAT_ID',
  CAHNGE_CHAT_LIST: 'CAHNGE_CHAT_LIST',
  ADD_BUBBLE_LIST: 'ADD_BUBBLE_LIST',
  CHANGE_CHAT: 'CHANGE_CHAT',
  SEND_CHAT: 'SEND_CHAT',
  CHANGE_SEND_MSG: 'CHANGE_SEND_MSG',
  CREATE_CHAT: 'CREATE_CHAT'
  // CHANGE_SEARCH_RESULTS: 'CHANGE_SEARCH_RESULTS',
  // CHANGE_LOCATION: 'CHANGE_LOCATION',
  // OPEN_PLAYER: 'OPEN_PLAYER',
  // CHANGE_PLAYER_SIZE: 'CHANGE_PLAYER_SIZE'
}
